### ISSUE TITLE
[Bug?]: 我的木鱼封禁截止时间显示错误

### ISSUE THREAD

**Issue by TKInvconry** [daizihan233/MiraiHanBot#10]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。

### 重现步骤

通过高频操作触发封禁机制，显示封禁时间与实际封禁时间不符

### 期望的结果是什么？

显示封禁截止时间与实际截止时间相符

### 实际的结果是什么？

实际操作出现问题，账号显示正常，但功德积累功能失效

**Comment by daizihan233** [comment]
确实
