### ISSUE TITLE
木魚功德數據反常

### ISSUE THREAD

**Issue by SM-N770FZKGTGY** [daizihan233/MiraiHanBot#13]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。

### 重现步骤

我的木鱼

### 期望的结果是什么？

@面包厂AM9分部
赛博账号：3496929815
账号状态：正常
木鱼等级：15
木鱼经验：434 / 626
当前速度：0.67s/周期
当前功德：75921（正常數值）
【敲电子木鱼，见机甲佛祖，取赛博真经】

### 实际的结果是什么？

@面包厂AM9分部
赛博账号：3496929815
账号状态：正常
木鱼等级：15
木鱼经验：434 / 626
当前速度：0.67s/周期
当前功德：1775921（不正常數據）
【敲电子木鱼，见机甲佛祖，取赛博真经】

**Comment by daizihan233** [comment]
在你提交Issue的时候这个Bug已经 **修好了**
