### ISSUE TITLE
撅括弧🐔

### ISSUE THREAD

**Issue by yll682** [daizihan233/MiraiHanBot#16]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能描述

![Uploading -3d122f577c719292.png…]()

**Comment by daizihan233** [comment]
你这图传了个啥啊
![)YF@}F 5XJBET`G` B`}L@Y](https://user-images.githubusercontent.com/72146468/212307012-e12d1090-b2d6-42fe-b5a5-457c375d0b64.jpg)

**Comment by daizihan233** [comment]
这Issue太烂力，重写罢（无慈悲）

**Comment by yll682** [comment]
![-3d122f577c719292](https://user-images.githubusercontent.com/57798097/212307230-3455281b-9d93-44ce-8894-2df0e0630271.png)
