### ISSUE TITLE
[Request++]: 敲木鱼

### ISSUE THREAD

**Issue by daizihan233** [daizihan233/MiraiHanBot#5]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。

### 功能名称

敲木鱼

### 描述

敲木鱼现在仅仅是注册而已，并不是真正得敲木鱼，应该把注册改一个触发词并实现手动敲木鱼

**Comment by yll682** [comment]
可以改成 获取木鱼 或者 给我木鱼 之类的关键词注册，敲木鱼可以用拍一拍，更有代入感（
